### PR TITLE
New York Times clone Project - Final submission

### PR DESCRIPTION
**Pull request by AymenBida**
### New York Times Project

In this project we did : 

- Prepare the environment to develop and the "linters" to test our code
- Prepare the contents of the website to be cloned (text, images...)
- Style and position all the elements
- Deploy the project with Github

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @jebitok-dev & @AymenBida **

Great job with the project so far, but there are still some changes to be made:
 
---
### Requested 🔴 
**General**

- [x] Every button should have the property `curser:  pointer;`

- [x] in this project you must use these three technieqes to position elements:
     flexbox, grid, float

**Navigation bar**
- [x] the hamburger and search icon should be buttons

**Video**

- [x] The video should have the same width as the text container

**Sidebar** 

- [x] the original page has a side bar like this one 
fkjy



---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by AymenBida** [comment]
### The New York Times Project

Changes we made to the project : 

- Added the property "cursor: pointer" to all the buttons
- Used all 3 techniques for positioning elements (float, grid, and flexbox)
- Added buttons for the icons in the Navigation bar
- Fixed the video width to be equal to the text container
- Added a fixed sidebar (editors' picks)

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @AymenBida and @jebitok-dev 

Good job implementing the change as requested by the previous TSE :+1: .
However, there's more to be done before this project can be approved.

## REQUIRED
- [x] The Editors' pick section should not be sticky
* [x] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Make the changes and submit for a new review

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by AymenBida** [comment]
### New York Times clone project

In this final submission we did : 

- Fix the sidebar so it's no longer sticky
- Change the ReadMe file
- Change the title of the pull request

**Comment by mimipeshy** [comment]
### STATUS :CHANGES REQUIRED :red_circle:  :recycle: 

Hey team :wave:  :wave:  good job on working on the feedback given by the TSE's. Before marking this project as complete lets work on the README file.

- [x]   The project should have a descriptive README.md  file
- Complete the getting started section of your README . This section should include the steps a user needs to use your project locally.
- Remove the sections of the README file that are not being used like install, Usage, Run tests, Deployment.

That's all :smile: , kindly submit another review when done.

Regards
Peris Ndanu
Feel free to reach out to me on slack if you have any qustions

**Comment by AymenBida** [comment]
### New York Times clone project
In this final submission we did :

- Update the ReadMe file (the getting started section)

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all project requirements and getting this project approved. :+1:

You can merge this branch into the main branch when you're ready and go on to your next project.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
